CREATE TABLE caught_pokemons
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    trainer_id BIGINT                                  NOT NULL,
    pokemon_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_caught_pokemons PRIMARY KEY (id)
);

CREATE TABLE gyms
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    trainer_id BIGINT UNIQUE                           NOT NULL,
    league     VARCHAR(255)                            NOT NULL,
    region     VARCHAR(255)                            NOT NULL,
    city       VARCHAR(255)                            NOT NULL,
    badge      VARCHAR(255)                            NOT NULL,
    image      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_gyms PRIMARY KEY (id)
);

CREATE TABLE pokemon_abilities
(
    pokemon_id BIGINT NOT NULL,
    ability    VARCHAR(255)
);

CREATE TABLE pokemon_evolutions
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    from_pokemon_id BIGINT                                  NOT NULL,
    to_pokemon_id   BIGINT                                  NOT NULL,
    trigger         VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_pokemon_evolutions PRIMARY KEY (id)
);

CREATE TABLE pokemon_types
(
    pokemon_id BIGINT NOT NULL,
    type       VARCHAR(255)
);

CREATE TABLE pokemons
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                 VARCHAR(255)                            NOT NULL,
    base_hp              INTEGER                                 NOT NULL,
    base_attack          INTEGER                                 NOT NULL,
    base_defense         INTEGER                                 NOT NULL,
    base_special_attack  INTEGER                                 NOT NULL,
    base_special_defense INTEGER                                 NOT NULL,
    base_speed           INTEGER                                 NOT NULL,
    species              VARCHAR(255)                            NOT NULL,
    description          TEXT,
    height               FLOAT                                   NOT NULL,
    weight               FLOAT                                   NOT NULL,
    image                VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_pokemons PRIMARY KEY (id)
);

CREATE TABLE trainers
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT                                  NOT NULL,
    title   VARCHAR(255)                            NOT NULL,
    bio     TEXT                                    NOT NULL,
    region  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_trainers PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    user_id BIGINT NOT NULL,
    role    VARCHAR(255)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR(255)                            NOT NULL,
    password      VARCHAR(255)                            NOT NULL,
    token_version BIGINT DEFAULT 0                        NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    avatar        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE won_badges
(
    gym_id     BIGINT NOT NULL,
    trainer_id BIGINT NOT NULL
);

ALTER TABLE gyms
    ADD CONSTRAINT uc_gyms_trainer UNIQUE (trainer_id);

ALTER TABLE trainers
    ADD CONSTRAINT uc_trainers_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE caught_pokemons
    ADD CONSTRAINT FK_CAUGHT_POKEMONS_ON_POKEMON FOREIGN KEY (pokemon_id) REFERENCES pokemons (id);

ALTER TABLE caught_pokemons
    ADD CONSTRAINT FK_CAUGHT_POKEMONS_ON_TRAINER FOREIGN KEY (trainer_id) REFERENCES trainers (id);

ALTER TABLE gyms
    ADD CONSTRAINT FK_GYMS_ON_TRAINER FOREIGN KEY (trainer_id) REFERENCES trainers (id);

ALTER TABLE pokemon_evolutions
    ADD CONSTRAINT FK_POKEMON_EVOLUTIONS_ON_FROM_POKEMON FOREIGN KEY (from_pokemon_id) REFERENCES pokemons (id);

ALTER TABLE pokemon_evolutions
    ADD CONSTRAINT FK_POKEMON_EVOLUTIONS_ON_TO_POKEMON FOREIGN KEY (to_pokemon_id) REFERENCES pokemons (id);

ALTER TABLE trainers
    ADD CONSTRAINT FK_TRAINERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE pokemon_abilities
    ADD CONSTRAINT fk_pokemon_abilities_on_pokemon_entity FOREIGN KEY (pokemon_id) REFERENCES pokemons (id);

ALTER TABLE pokemon_types
    ADD CONSTRAINT fk_pokemon_types_on_pokemon_entity FOREIGN KEY (pokemon_id) REFERENCES pokemons (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_on_user_entity FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE won_badges
    ADD CONSTRAINT fk_wonbad_on_gym_entity FOREIGN KEY (gym_id) REFERENCES gyms (id);

ALTER TABLE won_badges
    ADD CONSTRAINT fk_wonbad_on_trainer_entity FOREIGN KEY (trainer_id) REFERENCES trainers (id);