CREATE TABLE caught_pokemons
(
    id         BIGINT NOT NULL,
    trainer_id BIGINT NOT NULL,
    pokemon_id BIGINT NOT NULL,
    CONSTRAINT pk_caught_pokemons PRIMARY KEY (id)
);

CREATE TABLE pokemon_abilities
(
    pokemon_id BIGINT NOT NULL,
    ability    VARCHAR(255)
);

CREATE TABLE pokemon_types
(
    pokemon_id BIGINT NOT NULL,
    type       VARCHAR(255)
);

CREATE TABLE pokemon_evolutions
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    from_pokemon_id BIGINT                                  NOT NULL,
    to_pokemon_id   BIGINT                                  NOT NULL,
    trigger         VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_pokemon_evolutions PRIMARY KEY (id)
);

CREATE TABLE pokemons
(
    id                   BIGINT       NOT NULL,
    name                 VARCHAR(255) NOT NULL,
    base_hp               INTEGER      NOT NULL,
    base_attack          INTEGER      NOT NULL,
    base_defense         INTEGER      NOT NULL,
    base_special_attack  INTEGER      NOT NULL,
    base_special_defense INTEGER      NOT NULL,
    base_speed           INTEGER      NOT NULL,
    species              VARCHAR(255) NOT NULL,
    description          TEXT,
    height               FLOAT        NOT NULL,
    weight               FLOAT        NOT NULL,
    image                VARCHAR(255) NOT NULL,
    CONSTRAINT pk_pokemons PRIMARY KEY (id)
);

CREATE TABLE trainers
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_trainers PRIMARY KEY (id)
);

ALTER TABLE caught_pokemons
    ADD CONSTRAINT FK_CAUGHT_POKEMONS_ON_POKEMON FOREIGN KEY (pokemon_id) REFERENCES pokemons (id);

ALTER TABLE caught_pokemons
    ADD CONSTRAINT FK_CAUGHT_POKEMONS_ON_TRAINER FOREIGN KEY (trainer_id) REFERENCES trainers (id);

ALTER TABLE pokemon_abilities
    ADD CONSTRAINT fk_pokemon_abilities_on_pokemon_entity FOREIGN KEY (pokemon_id) REFERENCES pokemons (id);

ALTER TABLE pokemon_types
    ADD CONSTRAINT fk_pokemon_types_on_pokemon_entity FOREIGN KEY (pokemon_id) REFERENCES pokemons (id);

ALTER TABLE pokemon_evolutions
    ADD CONSTRAINT FK_POKEMON_EVOLUTIONS_ON_FROM_POKEMON FOREIGN KEY (from_pokemon_id) REFERENCES pokemons (id);

ALTER TABLE pokemon_evolutions
    ADD CONSTRAINT FK_POKEMON_EVOLUTIONS_ON_TO_POKEMON FOREIGN KEY (to_pokemon_id) REFERENCES pokemons (id);
