export const POKEMON_TYPES: Set<string> = new Set([
    "Bug",
    "Dark",
    "Dragon",
    "Electric",
    "Fairy",
    "Fighting",
    "Fire",
    "Flying",
    "Ghost",
    "Grass",
    "Ground",
    "Ice",
    "Normal",
    "Poison",
    "Psychic",
    "Rock",
    "Steel",
    "Water",
]);
export const TYPE_COLORS: Record<string, { bg: string; text: string; border: string }> = {
    Bug: {bg: "bg-[#A6B91A]", text: "text-white", border: "border-[#8A9A13]"},
    Dark: {bg: "bg-[#705746]", text: "text-white", border: "border-[#4E3D31]"},
    Dragon: {bg: "bg-[#6F35FC]", text: "text-white", border: "border-[#5326BD]"},
    Electric: {bg: "bg-[#F7D02C]", text: "text-zinc-900", border: "border-[#C7A623]"},
    Fairy: {bg: "bg-[#D685AD]", text: "text-white", border: "border-[#A36483]"},
    Fighting: {bg: "bg-[#C22E28]", text: "text-white", border: "border-[#91221D]"},
    Fire: {bg: "bg-[#EE8130]", text: "text-white", border: "border-[#B36124]"},
    Flying: {bg: "bg-[#A98FF3]", text: "text-white", border: "border-[#816DC1]"},
    Ghost: {bg: "bg-[#735797]", text: "text-white", border: "border-[#55406F]"},
    Grass: {bg: "bg-[#7AC74C]", text: "text-white", border: "border-[#5C9539]"},
    Ground: {bg: "bg-[#E2BF65]", text: "text-zinc-900", border: "border-[#AA8F4C]"},
    Ice: {bg: "bg-[#96D9D6]", text: "text-zinc-900", border: "border-[#71A4A2]"},
    Normal: {bg: "bg-[#A8A77A]", text: "text-white", border: "border-[#7E7D5B]"},
    Poison: {bg: "bg-[#A33EA1]", text: "text-white", border: "border-[#7A2E79]"},
    Psychic: {bg: "bg-[#F95587]", text: "text-white", border: "border-[#BB4065]"},
    Rock: {bg: "bg-[#B6A136]", text: "text-white", border: "border-[#897928]"},
    Steel: {bg: "bg-[#B7B7CE]", text: "text-zinc-900", border: "border-[#89899A]"},
    Water: {bg: "bg-[#6390F0]", text: "text-white", border: "border-[#4A6CB4]"},
};
